name: Deploy Node.js Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Verify node_modules creation
      - name: Verify node_modules
        run: |
          echo "Verifying node_modules directory..."
          ls -la node_modules

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step 3: Create .htaccess file
      - name: Create node module folder
        run: |
          echo "Creating node module folder..."
          npm install

      # Step 3: Create .htaccess file
      - name: Create .htaccess file
        run: |
          echo "Creating .htaccess file..."
          echo "${{ secrets.HTACCESS_CONTENT }}" > .htaccess
      
      - name: Create .env file
        run: |
          echo "Creating .env file..."
          echo "${{ secrets.ENV }}" > .env

      - name: Create config folder
        run: |
          echo "Creating config folder..."
          mkdir config
          cd config
          echo "${{ secrets.CONFIG_DB }}" > db.js

      # Step 4: Debugging - List files to ensure .htaccess and node_modules exist
      - name: List files before deployment
        run: ls -la

      # Step 5: Sync files to cPanel via FTP
      - name: Sync files to development
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.trimworldwide.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

