name: Deploy Node.js Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

  security_scan:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4
    steps:
      - uses: actions/checkout@v2
      - name: Security Scan
        uses: zricethezav/gitleaks-action@v1.5.0

  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout latest code
      - name: Get latest code
        uses: actions/checkout@v2

      # Step 3: Upload all files including .htaccess to cPanel via FTP
      - name: Sync files to development
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.trimworldwide.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      # Step 4: Trigger npm install on the server
      - name: Trigger npm install on server
        run: |
          echo "Triggering npm install via PHP script..."
          curl -X GET "https://rauf.trimworldwide.com/trigger.php"
