name: Deploy Node.js Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version

      # Step 3: Cache Node.js modules to speed up npm install
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci --production

      # Step 5: (Optional) Build the project
      #- name: Build the project
      #  run: npm run build

      # Step 6: Create .htaccess file
      - name: Create .htaccess file
        run: |
          echo "${{ secrets.HTACCESS_CONTENT }}" > .htaccess
      # Step 7: Install lftp for FTP deployment
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Step 8: Deploy to cPanel via FTP
      - name: Deploy to cPanel via FTP
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_PORT: ${{ secrets.FTP_PORT }} # Usually 21
        run: |
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; set ftp:ssl-allow no; mirror -R --delete --verbose . ."
        