name: Deploy Node.js Project to cPanel via FTP and Extract Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version

      # Step 3: Install dependencies (to create node_modules folder)
      - name: Install dependencies
        run: npm install

      # Step 5: Install lftp for FTP deployment
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Step 6: Upload compressed file to cPanel via FTP
      - name: Upload to cPanel via FTP
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        