name: Deploy Node.js Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use your desired Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (if applicable)
      #- name: Build the project
      #  run: npm run build

      # Step 5: Create .htaccess file
      - name: Create .htaccess file
        run: |
          echo "${{ secrets.HTACCESS_CONTENT }}" > .htaccess

      # Step 6: Deploy files to cPanel via FTP
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
        with:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER}}
